export { default as Navbar } from "./navbar/Navbar"
export { default as Header } from "./header/Header"
export { default as About } from "./about/About"
export { default as Skills } from "./skills/Skills"
export { default as Projects } from "./projects/Projects"
export { default as Contact } from "./contact/Contact"